interface AthleteInput {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  male: boolean;
  female: boolean;
  birthYear: number;
  team: string;
}

export const Athletes: AthleteInput[] = [
  {
    firstName: "Luke",
    lastName: "Williams",
    email: "luke@luke.com",
    password: "password",
    male: true,
    female: false,
    birthYear: 2000,
    team: "Rocks and Ropes",
  },
  {
    firstName: "Elissa",
    lastName: "James",
    email: "Elissa@Elissa.com",
    password: "password",
    male: false,
    female: true,
    birthYear: 2004,
    team: "Rocks and Ropes",
  },
  {
    firstName: "Justin",
    lastName: "Hanson",
    email: "Justin@Justin.com",
    password: "password",
    male: true,
    female: false,
    birthYear: 2000,
    team: "Rocks and Ropes",
  },
  {
    firstName: "Abby",
    lastName: "Roberts",
    email: "Abby@Abby.com",
    password: "password",
    male: false,
    female: true,
    birthYear: 2005,
    team: "Rocks and Ropes",
  },
  {
    firstName: "Jon",
    lastName: "Williams",
    email: "Jon@Jon.com",
    password: "password",
    male: true,
    female: false,
    birthYear: 2008,
    team: "Rocks and Ropes",
  },
  {
    firstName: "Tris",
    lastName: "Hampton",
    email: "Tris@Tris.com",
    password: "password",
    male: false,
    female: true,
    birthYear: 2009,
    team: "Rocks and Ropes",
  },
  {
    firstName: "Josh",
    lastName: "Flemmings",
    email: "Josh@Josh.com",
    password: "password",
    male: true,
    female: false,
    birthYear: 2007,
    team: "Rocks and Ropes",
  },
  {
    firstName: "Elsa",
    lastName: "Smith",
    email: "Elsa@Elsa.com",
    password: "password",
    male: false,
    female: true,
    birthYear: 2000,
    team: "Rocks and Ropes",
  },
  {
    firstName: "Brandon",
    lastName: "Abbey",
    email: "Brandon@Brandon.com",
    password: "password",
    male: true,
    female: false,
    birthYear: 2010,
    team: "Rocks and Ropes",
  },
  {
    firstName: "Dee",
    lastName: "Williams",
    email: "Dee@Dee.com",
    password: "password",
    male: false,
    female: true,
    birthYear: 2000,
    team: "Rocks and Ropes",
  },
  {
    firstName: "Jack",
    lastName: "Johnson",
    email: "Jack@Jack.com",
    password: "password",
    male: true,
    female: false,
    birthYear: 2008,
    team: "Rocks and Ropes",
  },
  {
    firstName: "Lucy",
    lastName: "Lee",
    email: "lucy@lucy.com",
    password: "password",
    male: false,
    female: true,
    birthYear: 2006,
    team: "Rocks and Ropes",
  },
  {
    firstName: "Sam",
    lastName: "Smith",
    email: "sam@sammm.com",
    password: "password",
    male: true,
    female: false,
    birthYear: 2005,
    team: "Rocks and Ropes",
  },
  {
    firstName: "Jessica",
    lastName: "Jennings",
    email: "jess@jess.com",
    password: "password",
    male: false,
    female: true,
    birthYear: 2000,
    team: "Rocks and Ropes",
  },
  {
    firstName: "Rob",
    lastName: "Williams",
    email: "rob@rob.com",
    password: "password",
    male: true,
    female: false,
    birthYear: 2000,
    team: "Rocks and Ropes",
  },
  {
    firstName: "Jenn",
    lastName: "Flanders",
    email: "jenn@jenn.com",
    password: "password",
    male: false,
    female: true,
    birthYear: 2008,
    team: "Rocks and Ropes",
  },
  {
    firstName: "Clint",
    lastName: "Stevens",
    email: "clint@clint.com",
    password: "password",
    male: true,
    female: false,
    birthYear: 2008,
    team: "Rocks and Ropes",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    email: "jane@jane.com",
    password: "password",
    male: false,
    female: true,
    birthYear: 2006,
    team: "Rocks and Ropes",
  },
  {
    firstName: "Billy",
    lastName: "Jacobs",
    email: "billy@billy.com",
    password: "password",
    male: true,
    female: false,
    birthYear: 2004,
    team: "Rocks and Ropes",
  },
  {
    firstName: "Sadie",
    lastName: "Johnson",
    email: "sadie@sadie.com",
    password: "password",
    male: false,
    female: true,
    birthYear: 2005,
    team: "Rocks and Ropes",
  },
];
